# Pipeline Step 2: Importing well information data

In [1]:
# As in Step 1, import the CSVs where the well information data is and combine into a single dataframe. 
# Ignore the 2007 file, the database it comes from is broken. 
import pandas as pd 
import glob
import matplotlib.pyplot as plt
%matplotlib inline

path ='/Users/krishankumar/Documents/csv' 
allFiles = glob.glob(path + "/*Wells.csv")

df = []

for f in allFiles:
    if '2007' in f:
        continue
    print(f)
    df.append(pd.read_csv(f , encoding = "ISO-8859-1", low_memory = False, dtype={'APINumber':str}))

/Users/krishankumar/Documents/csv/1977CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1978CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1979CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1980CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1981CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1982CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1983CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1984CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1985CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1986CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1987CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1988CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1989CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1990CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1991CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1992CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1993CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1994CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1995CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1996CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1997CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1998CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/1999CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2000CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2001CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2002CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2003CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2004CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2005CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2006CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2008CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2009CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2010CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2011CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2012CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2013CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2014CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2015CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2016CaliforniaOilandGasWells.csv
/Users/krishankumar/Documents/csv/2017CaliforniaOilandGasWells.csv

In [2]:
dfall = pd.concat(df, ignore_index=True)

In [3]:
df[1].shape

(250274, 25)

In [4]:
# We pull the relevant columns from the table. Wells are generally identified by their API number,
# but the wells are identified by PWT_ID in the production files. To match the correct API number to the corresponding
# data in the production data frame, we pull these two columns. 
temp = dfall[['APINumber','PWT__ID']].drop_duplicates()

In [5]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 275813 entries, 0 to 10184455
Data columns (total 2 columns):
APINumber    275813 non-null object
PWT__ID      275813 non-null int64
dtypes: int64(1), object(1)
memory usage: 6.3+ MB

In [6]:
temp.to_csv('wells.csv', index=False)

In [7]:
# Looking at what other data is present in this table. 
dfall.head()

,DistrictNumber,FieldCode,AreaCode,APINumber,WellStatus,Section,Subsection,Township,Range,BaseMeridian,...,OperatorName,OperatorStatus,OperatorReportingMethod,CountyName,PoolCode,WellTypeCode,PoolWellTypeStatus,SystemEntryDate,PoolName,PWT__ID
0,6,404,0,00100001,A,7.0,NaN,3S,3E,MD,...,E & B Natural Res. Mgmt. Corp.,A,99,Alameda,0,OG,A,4/1/1976,No Pool Breakdown,100097216
1,6,404,0,00120004,A,7.0,NaN,3S,3E,MD,...,E & B Natural Res. Mgmt. Corp.,A,99,Alameda,0,OG,A,4/1/1976,No Pool Breakdown,100097217
2,6,404,0,00120005,P,6.0,NaN,3S,3E,MD,...,Hershey Oil Corp.,I,41,Alameda,0,OG,P,4/1/1976,No Pool Breakdown,100143246
3,6,404,0,00120008,A,7.0,NaN,3S,3E,MD,...,E & B Natural Res. Mgmt. Corp.,A,99,Alameda,0,OG,P,4/1/1976,No Pool Breakdown,100143245
4,6,404,0,00120008,A,7.0,NaN,3S,3E,MD,...,E & B Natural Res. Mgmt. Corp.,A,99,Alameda,5,WD,A,4/1/1976,Greenville,100284671

In [9]:
dfall[dfall['APINumber'] == '03720044']

,DistrictNumber,FieldCode,AreaCode,APINumber,WellStatus,Section,Subsection,Township,Range,BaseMeridian,...,OperatorName,OperatorStatus,OperatorReportingMethod,CountyName,PoolCode,WellTypeCode,PoolWellTypeStatus,SystemEntryDate,PoolName,PWT__ID
207801,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
207802,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
458075,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
458076,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
708349,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
708350,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
958623,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
958624,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
1208897,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
1208898,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
1459171,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
1459172,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
1709445,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
1709446,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
1959719,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
1959720,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
2209993,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
2209994,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
2460267,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
2460268,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
2710541,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
2710542,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
2960815,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
2960816,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
3211089,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
3211090,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
3461363,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
3461364,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
3711637,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
3711638,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6461513,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
6461514,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
6711201,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
6711202,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
6960889,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
6960890,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
7210472,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
7210473,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
7460040,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
7460041,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
7709608,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
7709609,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
7959176,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
7959177,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Plains Expl. & Prod. Co.,A,96,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
8229836,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
8229837,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
8502889,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
8502890,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
8775942,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
8775943,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
9048995,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
9048996,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
9321760,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
9321761,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
9595070,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
9595071,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
9869653,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
9869654,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,Freeport-McMoRan O&G LLC,A,99,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134
10144783,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,"Sentinel Peak Resources CA, LLC",A,95,Los Angeles,0,OG,A,4/1/1976,No Pool Breakdown,100277384
10144784,1,54,3,03720044,A,29.0,NaN,1S,14W,SB,...,"Sentinel Peak Resources CA, LLC",A,95,Los Angeles,10,OG,P,4/1/1976,Miocene,100000134

In [10]:
# Determing how many PWT_IDs correspond to an API number. 
temp[temp.APINumber=='3720044']

Empty DataFrame
Columns: [APINumber, PWT__ID]
Index: []

In [11]:
temp

         APINumber    PWT__ID
0         00100001  100097216
1         00120004  100097217
2         00120005  100143246
3         00120008  100143245
4         00120008  100284671
5         00120009  100097225
6         00120012  100097219
7         00120014  100097220
8         00120018  100180911
9         00120031  100097221
10        00120031  100284670
11        00120036  100097222
12        00120041  100097223
13        00120043  100153813
14        00120044  100097224
15        00120056  100155865
16        00120062  100268354
17        00120063  100275737
18        00700002  100127852
19        00700002  100127860
20        00700003  100127849
21        00700003  100127859
22        00700004  100127856
23        00700008  100199097
24        00700009  100203625
25        00700010  100096794
26        00700011  100096795
27        00700012  100199929
28        00700013  100196019
29        00700016  100183218
...            ...        ...
10132109  03062704  100318013
10132110  03062705  100318011
10132111  03062706  100318012
10132112  03062707  100318010
10132113  03062708  100318048
10132114  03062711  100318063
10132115  03062712  100318066
10132116  03062713  100318068
10132117  03062714  100318064
10132118  03062715  100318067
10132119  03062716  100318065
10132120  03065259  100317748
10132167  03100079  100317725
10132913  03120527  100317775
10132914  03120528  100318022
10139004  03708239  100317759
10141984  03713628  100317815
10151915  05320159  100318032
10155529  05322483  100318040
10155530  05322483  100318041
10155531  05322484  100318042
10155532  05322484  100318043
10155533  05322485  100318046
10155534  05322485  100318047
10155535  05322486  100318044
10155536  05322486  100318045
10162788  06900158  100317961
10171214  08322599  100317738
10171700  08322941  100318007
10184455  23702429  100317774

[275813 rows x 2 columns]

In [12]:
temp.shape

(275813, 2)